# Generated by Django 3.0.5 on 2020-04-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
